server:
  port: 9000
  servlet:
    context-path: /

spring:
  jwt:
    headerKey: authorization
    secret: yhchoi!@#
    before_len: 8
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true      
        ddl-auto: none
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy      
        jdbc.time_zone: Asia/Seoul
  datasource:
     driver-class-name: org.mariadb.jdbc.Driver
     url: jdbc:mariadb://unknown.cmoozwqocg37.ap-northeast-2.rds.amazonaws.com:3306/unknown_db?autoReconnection=true
     jdbc-url: jdbc:mariadb://unknown.cmoozwqocg37.ap-northeast-2.rds.amazonaws.com:3306/unknown_db?autoReconnection=true
     username: sysadmins
     password: eWhjaG9pODAzMQ==
     hikari:
      maximum-pool-size: 5